[project]
name = "mazegen"
version = "2.0.0"
description = "Generate a maze"
authors = [
    { name = "fetraand", email = "fetraand@student.42antananarivo.mg" },
    { name = "hasandri", email = "hasandri@student.42antananarivo.mg" }
]
requires-python = ">=3.10"
dependencies = []


[tool.poetry.group.dev.dependencies]
flake8 = ">=7.3.0,<8.0.0"
mypy = ">=2.3.0,<3.0.0"
flake8-docstrings = ">=1.7.0,<2.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"